"""LLM-powered formula generator — uses an LLM to produce SymPy-parseable
formulas from a brief, falling back to templates when no API key is set.

The LLM is asked to produce formulas in a constrained format:
  * Single-variable (x) or two-variable (x, y)
  * Using only: +, -, *, /, **, sin, cos, exp, log, sqrt, abs
  * No Python syntax (no def, lambda, import, print)
  * Must be parseable by SymPy's parse_expr

The prompt includes examples of valid formulas and the falsifier
pattern for each mechanism family.
"""

from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass, field
from typing import Any

from ..sympy_mcp.server import tool_parse

__all__ = ["LLMFormula", "generate_formulas_llm", "LLM_GENERATION_AVAILABLE"]


def LLM_GENERATION_AVAILABLE() -> bool:
    """Check if an LLM API key is configured."""
    return bool(
        os.environ.get("ANTHROPIC_API_KEY")
        or os.environ.get("OPENAI_API_KEY")
        or os.environ.get("OPENROUTER_API_KEY")
    )


@dataclass
class LLMFormula:
    """A formula generated by an LLM."""
    name: str
    formula: str
    falsifier: str
    mechanism_family: str
    rationale: str = ""
    primitives: list[str] = field(default_factory=list)


# ────────────────────────────────────────────────────────────────────
# Prompt
# ────────────────────────────────────────────────────────────────────

_FORMULA_SYSTEM_PROMPT = """You are a mathematical formula generator for a GTM (Go-To-Market) idea validation system.

Given a strategic brief, generate candidate formulas that represent novel GTM mechanisms.

RULES:
1. Use only: x, y (variables), +, -, *, /, **, sin, cos, exp, log, sqrt, abs
2. NO Python syntax: no def, lambda, import, print, __builtins__
3. Each formula must be parseable by SymPy
4. Each formula must have a falsifier (a test that would disprove it)
5. Each formula must have a mechanism_family

Output JSON array:
[
  {
    "name": "short_name",
    "formula": "x**2 + 3*sin(x)",
    "falsifier": "test condition that would invalidate this",
    "mechanism_family": "financial|distribution|adoption|retention|pricing",
    "rationale": "why this formula captures a novel mechanism",
    "primitives": ["primitive1", "primitive2"]
  }
]

Generate exactly N formulas. Be creative but mathematically sound.
"""

_EXAMPLES = """
Example formulas:
  - "x**2 * exp(-x/10)" — growth with natural decay
  - "log(1 + x) / (1 + exp(-x))" — saturating adoption curve
  - "sin(x * 0.1) * x" — oscillating growth
  - "x / (1 + x**2)" — diminishing returns
  - "sqrt(x) * (1 + 0.1 * sin(x))" — steady growth with periodic variation
"""


# ────────────────────────────────────────────────────────────────────
# LLM callers
# ────────────────────────────────────────────────────────────────────


def _call_anthropic(prompt: str, n: int) -> str:
    """Call Anthropic API."""
    import urllib.request

    api_key = os.environ["ANTHROPIC_API_KEY"]
    body = json.dumps({
        "model": "claude-sonnet-4-20250514",
        "max_tokens": 2000,
        "messages": [{"role": "user", "content": prompt}],
    }).encode()

    req = urllib.request.Request(
        "https://api.anthropic.com/v1/messages",
        data=body,
        headers={
            "Content-Type": "application/json",
            "x-api-key": api_key,
            "anthropic-version": "2023-06-01",
        },
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        data = json.loads(resp.read())
    return data["content"][0]["text"]


def _call_openai(prompt: str, n: int) -> str:
    """Call OpenAI-compatible API (works with OpenRouter too)."""
    import urllib.request

    api_key = os.environ.get("OPENAI_API_KEY") or os.environ.get("OPENROUTER_API_KEY", "")
    base_url = os.environ.get("OPENAI_BASE_URL", "https://api.openai.com/v1")

    body = json.dumps({
        "model": os.environ.get("OPENAI_MODEL", "gpt-4o-mini"),
        "messages": [{"role": "user", "content": prompt}],
        "max_tokens": 2000,
    }).encode()

    req = urllib.request.Request(
        f"{base_url}/chat/completions",
        data=body,
        headers={
            "Content-Type": "application/json",
            "Authorization": f"Bearer {api_key}",
        },
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        data = json.loads(resp.read())
    return data["choices"][0]["message"]["content"]


def _extract_json(text: str) -> list[dict[str, Any]]:
    """Extract JSON array from LLM response text."""
    # Try to find JSON array in the response
    match = re.search(r"\[.*\]", text, re.DOTALL)
    if match:
        try:
            return json.loads(match.group())
        except json.JSONDecodeError:
            pass
    return []


def _validate_formula(formula_str: str) -> bool:
    """Check if a formula string is parseable by SymPy."""
    result = tool_parse(formula_str)
    return result.get("status") == "OK"


# ────────────────────────────────────────────────────────────────────
# Public API
# ────────────────────────────────────────────────────────────────────


def generate_formulas_llm(
    brief: str,
    n: int = 9,
    provider: str | None = None,
) -> list[LLMFormula]:
    """Generate formulas using an LLM.

    Falls back to empty list if no API key is configured.
    Validates each formula against SymPy before returning.
    """
    if provider is None:
        if os.environ.get("ANTHROPIC_API_KEY"):
            provider = "anthropic"
        elif os.environ.get("OPENAI_API_KEY") or os.environ.get("OPENROUTER_API_KEY"):
            provider = "openai"
        else:
            return []

    prompt = f"{_FORMULA_SYSTEM_PROMPT}\n\n{_EXAMPLES}\n\nBrief: {brief}\n\nGenerate {n} formulas."

    try:
        if provider == "anthropic":
            raw = _call_anthropic(prompt, n)
        else:
            raw = _call_openai(prompt, n)
    except Exception:
        return []

    items = _extract_json(raw)
    formulas: list[LLMFormula] = []

    for item in items:
        formula_str = item.get("formula", "")
        if not _validate_formula(formula_str):
            continue

        formulas.append(LLMFormula(
            name=item.get("name", f"llm_{len(formulas)}"),
            formula=formula_str,
            falsifier=item.get("falsifier", ""),
            mechanism_family=item.get("mechanism_family", "unknown"),
            rationale=item.get("rationale", ""),
            primitives=item.get("primitives", []),
        ))

        if len(formulas) >= n:
            break

    return formulas
